# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test APIs integrated in BTE

on:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest requests
    - name: Test with pytest
      run: |
        python -m pytest tests/cron --disable-warnings 
    # - name: Coverage
    #   run: |
    #     coverage run -m pytest tests --disable-warnings --ignore=tests/test_apis
    #     coverage xml -o coverage.xml
    #     bash <(wget -q -O - https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml --partial
