# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test BioThings Explorer Python Package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  test_and_coverage:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Test with pytest
    #   run: |
    #     python -m pytest tests --disable-warnings --ignore=tests/test_apis
    - name: Test and Coverage
      run: |
        coverage run -m pytest tests --disable-warnings --ignore=tests/test_apis
        coverage xml -o coverage.xml
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage.xml
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    needs: test_and_coverage
    steps:
      - uses: actions/checkout@master
      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

      